name: Test & Deploy
on: 
  push:
    branches:
      -main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

# all the comments (?)
# all the comments written by a user
# most voted comment from a user
# change the previous tests which didn't allow negative votes - downvotes 
# all the articles under a topic
# 